version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports: 
      - '$PORT:$PORT'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - volumes/truphone-api:/data/postgres/truphone-api:rw%%